/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.2.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// TerminalHold struct for TerminalHold
type TerminalHold struct {
	Name string `json:"name"`
	Status string `json:"status"`
	// Text description from the terminal (if any)
	Description string `json:"description,omitempty"`
}
