/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.1.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// InlineResponse2008 struct for InlineResponse2008
type InlineResponse2008 struct {
	Data []Container `json:"data,omitempty"`
	Included []Shipment `json:"included,omitempty"`
	Links Links `json:"links,omitempty"`
	Meta Meta `json:"meta,omitempty"`
}
