/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.2.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// Webhook struct for Webhook
type Webhook struct {
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes WebhookAttributes `json:"attributes,omitempty"`
}
