/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.1.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// TrackingRequestsDataAttributes struct for TrackingRequestsDataAttributes
type TrackingRequestsDataAttributes struct {
	RequestType string `json:"request_type"`
	RequestNumber string `json:"request_number"`
	Scac string `json:"scac"`
	// Optional list of reference numbers to be added to the shipment when tracking request completes
	RefNumbers []string `json:"ref_numbers,omitempty"`
}
