/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.1.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
import (
	"time"
)
// TransportEventAttributes struct for TransportEventAttributes
type TransportEventAttributes struct {
	Event string `json:"event,omitempty"`
	VoyageNumber string `json:"voyage_number,omitempty"`
	Timestamp time.Time `json:"timestamp,omitempty"`
	// IANA tz
	Timezone string `json:"timezone,omitempty"`
	// UNLOCODE of the event location
	LocationLocode string `json:"location_locode,omitempty"`
}
