/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.1.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// TransportEventRelationships struct for TransportEventRelationships
type TransportEventRelationships struct {
	Shipment ContainerRelationshipsShipment `json:"shipment,omitempty"`
	Location TransportEventRelationshipsLocation `json:"location,omitempty"`
	Vessel TransportEventRelationshipsVessel `json:"vessel,omitempty"`
	Terminal TransportEventRelationshipsTerminal `json:"terminal,omitempty"`
	Container TransportEventRelationshipsContainer `json:"container,omitempty"`
	 string `json:",omitempty"`
}
