/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.2.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// EstimatedEventRelationships struct for EstimatedEventRelationships
type EstimatedEventRelationships struct {
	Shipment EstimatedEventRelationshipsShipment `json:"shipment"`
	Port TerminalRelationshipsPort `json:"port,omitempty"`
	Vessel EstimatedEventRelationshipsVessel `json:"vessel,omitempty"`
}
