/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.1.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// InlineResponse2009 struct for InlineResponse2009
type InlineResponse2009 struct {
	Data Container `json:"data,omitempty"`
	Included []Shipment `json:"included,omitempty"`
}
