/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.1.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// VesselAttributes struct for VesselAttributes
type VesselAttributes struct {
	Name string `json:"name,omitempty"`
	Imo string `json:"imo,omitempty"`
	Mmsi string `json:"mmsi,omitempty"`
}
