/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.1.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// RailTerminal struct for RailTerminal
type RailTerminal struct {
	Id string `json:"id,omitempty"`
	Relationships RailTerminalRelationships `json:"relationships,omitempty"`
	Attributes TerminalAttributes `json:"attributes"`
	Type string `json:"type,omitempty"`
}
