/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.1.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// ContainerRelationships struct for ContainerRelationships
type ContainerRelationships struct {
	TransportEvents ContainerRelationshipsTransportEvents `json:"transport_events,omitempty"`
	Shipment ContainerRelationshipsShipment `json:"shipment,omitempty"`
	PodTerminal ContainerRelationshipsPodTerminal `json:"pod_terminal,omitempty"`
}
