/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.1.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// WebhookAttributes struct for WebhookAttributes
type WebhookAttributes struct {
	// https end point
	Url string `json:"url"`
	// whether the webhook will be delivered when events are triggered
	Active bool `json:"active"`
	Events []string `json:"events"`
	// A random token that will sign all delivered webhooks
	Secret string `json:"secret"`
}
