/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.2.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
import (
	"time"
)
// ContainerUpdatedEventAttributes struct for ContainerUpdatedEventAttributes
type ContainerUpdatedEventAttributes struct {
	// A hash of all the changed attributes with the values being an array of the before and after. E.g.  `{\"pickup_lfd\": [null, \"2020-05-20\"]}`  The current attributes that can be alerted on are: - `available_for_pickup` - `pickup_lfd` - `fees_at_pod_terminal` - `holds_at_pod_terminal`
	Changeset map[string]interface{} `json:"changeset"`
	Timestamp time.Time `json:"timestamp"`
	// IANA tz 
	Timezone string `json:"timezone,omitempty"`
}
