/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.1.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
import (
	"time"
)
// EstimatedEventAttributes struct for EstimatedEventAttributes
type EstimatedEventAttributes struct {
	Event string `json:"event"`
	EstimatedTimestamp time.Time `json:"estimated_timestamp"`
	VoyageNumber string `json:"voyage_number,omitempty"`
}
