/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.1.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// InlineResponse2005 struct for InlineResponse2005
type InlineResponse2005 struct {
	Data []Webhook `json:"data,omitempty"`
	Meta Meta `json:"meta,omitempty"`
	Links Links `json:"links,omitempty"`
}
