/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.1.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// TrackingRequestRelationships struct for TrackingRequestRelationships
type TrackingRequestRelationships struct {
	TrackedObject TrackingRequestRelationshipsTrackedObject `json:"tracked_object,omitempty"`
}
