/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.2.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// TerminalAttributes struct for TerminalAttributes
type TerminalAttributes struct {
	Name string `json:"name"`
	Nickname string `json:"nickname,omitempty"`
	// CBP FIRMS Code or CBS Sublocation Code
	FirmsCode string `json:"firms_code,omitempty"`
}
