/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.2.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// InlineResponse2001 struct for InlineResponse2001
type InlineResponse2001 struct {
	Data Shipment `json:"data,omitempty"`
	Included []interface{} `json:"included,omitempty"`
}
