/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.2.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
import (
	"time"
)
// ShipmentAttributes struct for ShipmentAttributes
type ShipmentAttributes struct {
	BillOfLadingNumber string `json:"bill_of_lading_number"`
	RefNumbers []string `json:"ref_numbers,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	// `unreleased`
	Tags []string `json:"tags,omitempty"`
	// UN/LOCODE
	PortOfLadingLocode string `json:"port_of_lading_locode,omitempty"`
	PortOfLadingName string `json:"port_of_lading_name,omitempty"`
	// UN/LOCODE
	PortOfDischargeLocode string `json:"port_of_discharge_locode,omitempty"`
	PortOfDischargeName string `json:"port_of_discharge_name,omitempty"`
	// UN/LOCODE
	DestinationLocode string `json:"destination_locode,omitempty"`
	DestinationName string `json:"destination_name,omitempty"`
	ShippingLineScac string `json:"shipping_line_scac,omitempty"`
	ShippingLineName string `json:"shipping_line_name,omitempty"`
	PodVesselName string `json:"pod_vessel_name,omitempty"`
	PodVesselImo string `json:"pod_vessel_imo,omitempty"`
	PodVoyageNumber string `json:"pod_voyage_number,omitempty"`
	PolEtdAt *time.Time `json:"pol_etd_at,omitempty"`
	PolAtdAt *time.Time `json:"pol_atd_at,omitempty"`
	PodEtaAt *time.Time `json:"pod_eta_at,omitempty"`
	PodAtaAt *time.Time `json:"pod_ata_at,omitempty"`
	DestinationEtaAt *time.Time `json:"destination_eta_at,omitempty"`
	DestinationAtaAt *time.Time `json:"destination_ata_at,omitempty"`
	// IANA tz
	PolTimezone *string `json:"pol_timezone,omitempty"`
	// IANA tz
	PodTimezone *string `json:"pod_timezone,omitempty"`
	// IANA tz
	DestinationTimezone *string `json:"destination_timezone,omitempty"`
	// When Terminal49 last tried to update the shipment status from the shipping line
	LineTrackingLastAttemptedAt *time.Time `json:"line_tracking_last_attempted_at,omitempty"`
	// When Terminal49 last successfully updated the shipment status from the shipping line
	LineTrackingLastSucceededAt *time.Time `json:"line_tracking_last_succeeded_at,omitempty"`
	// When Terminal49 stopped checking at the shipping line
	LineTrackingStoppedAt *time.Time `json:"line_tracking_stopped_at,omitempty"`
	// The reason Terminal49 stopped checking
	LineTrackingStoppedReason *string `json:"line_tracking_stopped_reason,omitempty"`
}
