/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.2.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// ShippingLineAttributes struct for ShippingLineAttributes
type ShippingLineAttributes struct {
	Scac string `json:"scac"`
	Name string `json:"name"`
	ShortName string `json:"short_name"`
	BillOfLadingTrackingSupport bool `json:"bill_of_lading_tracking_support"`
	BookingNumberTrackingSupport bool `json:"booking_number_tracking_support"`
	ContainerNumberTrackingSupport bool `json:"container_number_tracking_support"`
}
