/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.2.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
import (
	"time"
)
// EstimatedEventAttributes struct for EstimatedEventAttributes
type EstimatedEventAttributes struct {
	// When the estimated event was created
	CreatedAt time.Time `json:"created_at"`
	EstimatedTimestamp time.Time `json:"estimated_timestamp"`
	Event string `json:"event"`
	// UNLOCODE of the event location
	LocationLocode *string `json:"location_locode,omitempty"`
	// IANA tz
	Timezone *string `json:"timezone,omitempty"`
	VoyageNumber *string `json:"voyage_number,omitempty"`
}
