/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.2.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// InlineResponse20013 struct for InlineResponse20013
type InlineResponse20013 struct {
	Data ShippingLine `json:"data,omitempty"`
}
