/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.1.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// WebhooksIdDataAttributes struct for WebhooksIdDataAttributes
type WebhooksIdDataAttributes struct {
	// The URL of the webhook endpoint.
	Url string `json:"url,omitempty"`
	// The list of events to enable for this endpoint. You may specify `['*']` to enable all events.
	Events []string `json:"events,omitempty"`
	Active bool `json:"active,omitempty"`
	// Optional custom headers to pass with each webhook invocation
	Headers []WebhooksIdDataAttributesHeaders `json:"headers,omitempty"`
}
