/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.2.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// TransportEventRelationshipsVesselData struct for TransportEventRelationshipsVesselData
type TransportEventRelationshipsVesselData struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
