/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.2.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// InlineResponse20012 struct for InlineResponse20012
type InlineResponse20012 struct {
	Data []ShippingLine `json:"data,omitempty"`
	Links Links `json:"links,omitempty"`
}
