/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.1.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// TrackingRequest struct for TrackingRequest
type TrackingRequest struct {
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes TrackingRequestAttributes `json:"attributes,omitempty"`
	Relationships TrackingRequestRelationships `json:"relationships,omitempty"`
}
