/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.1.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
import (
	"time"
)
// RawEventAttributes struct for RawEventAttributes
type RawEventAttributes struct {
	// Normalized string representing the event
	Event string `json:"event,omitempty"`
	// The event name as returned by the carrier
	OriginalEvent string `json:"original_event,omitempty"`
	// The date of the event at the event location when no time information is available. 
	ActualOn string `json:"actual_on,omitempty"`
	// The estimated date of the event at the event location when no time information is available. 
	EstimatedOn string `json:"estimated_on,omitempty"`
	// The datetime the event transpired in UTC
	ActualAt time.Time `json:"actual_at,omitempty"`
	// The estimated datetime the event will occur in UTC
	EstimatedAt time.Time `json:"estimated_at,omitempty"`
	// IANA TZ where the event occured
	Timezone string `json:"timezone,omitempty"`
	// When the raw_event was created in UTC
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The city or facility name of the event location
	LocationName string `json:"location_name,omitempty"`
	// UNLOCODE of the event location
	LocationLocode string `json:"location_locode,omitempty"`
	// The name of the vessel where applicable
	VesselName string `json:"vessel_name,omitempty"`
	// The IMO of the vessel where applicable
	VesselImo string `json:"vessel_imo,omitempty"`
	// The order of the event. Thishelpful when only dates (i.e. actual_on) are available.
	Index int32 `json:"index,omitempty"`
	VoyageNumber string `json:"voyage_number,omitempty"`
}
