/*
 * Terminal49 API Reference
 *
 * The Terminal 49 API offers a convenient way to programmatically track your shipments from origin to destination.
 *
 * API version: 0.1.0
 * Contact: support@terminal49.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package terminal49
// WebhooksIdDataAttributesHeaders struct for WebhooksIdDataAttributesHeaders
type WebhooksIdDataAttributesHeaders struct {
	// The name of the header. (Please not this will be auto-capitalized) 
	Name string `json:"name,omitempty"`
	// The value to pass for the header 
	Value string `json:"value,omitempty"`
}
